package com.aeox.auth.repository;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import javax.transaction.Transactional;

import com.aeox.auth.entity.Role;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
public class RoleRepositoryPanacheImplTest {

    private RoleRepositoryPanacheImpl underTest;

    @BeforeEach
    public void setup() {
        underTest = new RoleRepositoryPanacheImpl();
    }

    @Test
    @Transactional
    public void when_role_persist_then_id_created_at_autogenerated() {
        var role = new Role();
        underTest.persist(role);
        assertNotNull(role.getId());
        assertNotNull(role.getCreatedAt());
    }
}
